### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by wolfgang1021** [Alpaca-zip/ultralytics_ros#12]
hello Alpaca-zip,
Thank you for your program.
I encountered the following error when running `tracker_node`, it seems that `ros_numpy` is not compatible.
Looking forward to your response.

Error:
Traceback (most recent call last):
  File "/home/gh/v8_0.2/devel/lib/v8/track.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/gh/v8_0.2/src/v8/src/track.py", line 3, in <module>
    import ros_numpy
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/__init__.py", line 7, in <module>
    from . import point_cloud2
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/point_cloud2.py", line 224, in <module>
    def get_xyz_points(cloud_array, remove_nans=True, dtype=np.float):
  File "/home/gh/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by Alpaca-zip** [comment]
Thank you @wolfgang1021  for your valuable report.

According to NumPy's release notes, `numpy.float` was deprecated in `v1.20` and these were completely removed in `v1.24.0`.
Therefore, if you are getting the following error, I assume that your version of NumPy is `v1.24.0` or higher.

`AttributeError: module 'numpy' has no attribute 'float'.`

The solution to this is to downgrade NumPy. I believe it works perfectly with `v1.23.4`, for example, as specified in [requirements.txt](https://github.com/Alpaca-zip/ultralytics_ros/blob/noetic-devel/requirements.txt). Try downgrading to NumPy `v1.23.4` with the following command.

`python3 -m pip uninstall numpy && python3 -m pip install --ignore-installed numpy==1.23.4`

Best regards,

**Comment by Alpaca-zip** [comment]
Have you made any progress? Feel free to re-open this issue if you have any more problems.
Thank you.
